packages:
  - "shell"
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - esbuild

catalog:
  "@eslint/js": ^9.39.2
  "@eslint/compat": ^2.0.0
  "@lucide/svelte": ^0.562.0
  "@sveltejs/adapter-node": ^5.4.0
  "@sveltejs/kit": ^2.49.2
  "@sveltejs/vite-plugin-svelte": ^6.2.1
  "@tailwindcss/vite": ^4.1.18
  "@types/node": ^25.0.3
  "@vitest/browser-playwright": ^4.0.16
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.13.1
  globals: ^16.5.0
  mode-watcher: ^1.1.0
  playwright: ^1.57.0
  vitest: ^4.0.16
  vitest-browser-svelte: ^2.0.1
  vite: ^7.3.0
  prettier: ^3.7.4
  prettier-plugin-svelte: ^3.4.1
  prettier-plugin-tailwindcss: ^0.7.2
  shadcn-svelte: ^1.1.0
  svelte: ^5.46.0
  svelte-check: ^4.3.5
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  typescript-eslint: ^8.50.1
